# Practice Assignment 3.2: Introduction to NumPy

## Objective
- Create and manipulate NumPy arrays.
- Perform basic mathematical and statistical operations.
- Understand the benefits of using NumPy for large data sets.

## Part 1: Creating and Inspecting Arrays
1. Import the NumPy library.
2. Create a 1D array of numbers from 0–9.
3. Create a 2D array with the following structure:
```python
[[1, 2, 3],
 [4, 5, 6]]
```
4. Use `.shape` and `.dtype` to inspect both arrays.
5. Convert the 1D array into a 2D array of shape (2,5) using `.reshape()`.

In [2]:
# 1. Import the NumPy library.
import numpy as np

In [5]:
# 2. Create a 1D array of numbers from 0–9.
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# 3. Create a 2D array with the following structure:
# ```python
# [[1, 2, 3],
#  [4, 5, 6]]
# ```
arr2 = np.arange(1, 7).reshape(2, 3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# 4. Use `.shape` and `.dtype` to inspect both arrays.
arr.shape, arr.dtype

((2, 3), dtype('int64'))

In [15]:
# 5. Convert the 1D array into a 2D array of shape (2,5) using `.reshape()`.
arr3 = np.arange(1, 11).reshape(2, 5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Part 2: Array Indexing and Slicing
1. From the 2D array:
   - Extract the second row.
   - Extract the first column.
   - Extract the element located in the second row, third column.
2. From the reshaped array (2x5), slice:
   - All elements except the first column.
   - The first three columns only.

In [29]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
# Extract 2nd row
arr3[1]

array([ 6,  7,  8,  9, 10])

In [22]:
# Extract 1st column
arr3[:, 0]

array([1, 6])

In [32]:
# Extract element located in second row and thrid column
elem = arr[1, 2]
elem

np.int64(8)

In [34]:
# Reshape 
arrx = arr3.reshape(5, 2)
arrx

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [36]:
# Exclude 1st column
arr3[:, 1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [37]:
# 1st 3 columns only
arr3[:, :3]

array([[1, 2, 3],
       [6, 7, 8]])

## Part 3: Array Operations
1. Create an array `a = np.arange(1, 6)` and another array `b = np.arange(10, 15)`.
2. Perform the following:
   - Element-wise addition of `a` and `b`.
   - Element-wise multiplication of `a` and `b`.
   - Find the sum of all elements in `a`.
   - Find the mean of `b`.
   - Find the maximum and minimum values in both arrays.

In [41]:
a = np.arange(1, 6)
b = np.arange(10, 15)
a, b

(array([1, 2, 3, 4, 5]), array([10, 11, 12, 13, 14]))

In [42]:
# Element-wise addition
a + b

array([11, 13, 15, 17, 19])

In [43]:
# Element wise multiplication
a*b

array([10, 22, 36, 52, 70])

In [46]:
# Sum of all elements in a
np.sum(a)

np.int64(15)

In [47]:
# Mean of b
np.mean(b)

np.float64(12.0)

In [48]:
# Find maximum and minimum values 
np.max(a), np.min(b)

(np.int64(5), np.int64(10))

## Part 4: Handling Large Datasets
1. Create an array with 1 million random numbers using:
```python
data = np.random.rand(1000000)
```
2. Perform the following:
   - Find the mean and standard deviation of this large array.

In [49]:
npx = np.random.rand(100000)
npx

array([0.70585661, 0.3193635 , 0.78453462, ..., 0.34341961, 0.58056851,
       0.67151892], shape=(100000,))

In [52]:
np.mean(npx), np.std(npx)

(np.float64(0.5007064077438881), np.float64(0.28852318846742475))

## Part 5: Practice Challenges
1. Create a 3D array of shape (3, 3, 3) and fill it with random integer values between 0–100. 
```python
array_3d = np.random.randint(0, 101, (3, 3, 3))
```
   Find:
   - The total sum of the array.
   - The maximum and minimum along the first axis.

2. Create a linear space of 20 numbers from 1 to 100 and reshape it into a 4×5 array.
```python
linear_array = np.linspace(1, 100, 20).reshape(4, 5)
```
   - Find the standard deviation of all the columns.

In [55]:
array_3d = np.random.randint(0, 101, (3, 3, 3))
array_3d

array([[[44, 26,  2],
        [80, 39, 96],
        [72, 93, 28]],

       [[27, 26, 65],
        [15, 42, 51],
        [75, 10, 64]],

       [[76, 17, 41],
        [ 3, 85, 37],
        [28, 13,  4]]])

In [56]:
# Sum of array
np.sum(array_3d)

np.int64(1159)

In [57]:
# Maximum and minimum along first axis 
np.max(array_3d, axis=0)

array([[76, 26, 65],
       [80, 85, 96],
       [75, 93, 64]])

In [58]:
np.min(array_3d, axis=0)

array([[27, 17,  2],
       [ 3, 39, 37],
       [28, 10,  4]])

In [61]:
linear_array = np.linspace(1, 100, 20).reshape(4, 5)
linear_array

array([[  1.        ,   6.21052632,  11.42105263,  16.63157895,
         21.84210526],
       [ 27.05263158,  32.26315789,  37.47368421,  42.68421053,
         47.89473684],
       [ 53.10526316,  58.31578947,  63.52631579,  68.73684211,
         73.94736842],
       [ 79.15789474,  84.36842105,  89.57894737,  94.78947368,
        100.        ]])

In [63]:
# Find std of all columns 
np.std(linear_array, axis=0)

array([29.1277276, 29.1277276, 29.1277276, 29.1277276, 29.1277276])

## Part 6: Challenge Exercise: Real-World Application

1. Create a 2D numpy array
```python
np.array([
    [25, 175, 70],  # [Age, Height, Weight]
    [30, 180, 80],
    [22, 165, 65],
    [28, 172, 75],
    [35, 178, 85]])

2. Compute the statistics for each feature (Age, Height, Weight)

3. Calculate the correlation matrix ()

In [66]:
arr_data = np.array([
    [25, 175, 70],  # [Age, Height, Weight]
    [30, 180, 80],
    [22, 165, 65],
    [28, 172, 75],
    [35, 178, 85]
])
print("Dataset (Age, Height, Weight):\n", arr_data)

Dataset (Age, Height, Weight):
 [[ 25 175  70]
 [ 30 180  80]
 [ 22 165  65]
 [ 28 172  75]
 [ 35 178  85]]


In [67]:
# 2. Compute the statistics for each feature (Age, Height, Weight)
age_mean = np.mean(arr_data[:, 0])
height_mean = np.mean(arr_data[:, 1])
weight_mean = np.mean(arr_data[:, 2])
print(f"Mean Age: {age_mean}, Mean Height: {height_mean}, Mean Weight: {weight_mean}")

age_std = np.std(arr_data[:, 0])
height_std = np.std(arr_data[:, 1])
weight_std = np.std(arr_data[:, 2])
print(f"Std Dev Age: {age_std}, Std Dev Height: {height_std}, Std Dev Weight: {weight_std}")

Mean Age: 28.0, Mean Height: 174.0, Mean Weight: 75.0
Std Dev Age: 4.427188724235731, Std Dev Height: 5.253570214625479, Std Dev Weight: 7.0710678118654755


In [68]:
# 3. Calculate the correlation matrix
corr_matrix = np.corrcoef(arr_data.T)  # Transpose to compute correlation between columns
print("Correlation Matrix:\n", corr_matrix)

Correlation Matrix:
 [[1.         0.78250805 0.99025868]
 [0.78250805 1.         0.83449195]
 [0.99025868 0.83449195 1.        ]]
