# Numpy tutorials for beginners

![alt text](https://miro.medium.com/v2/resize:fit:1292/format:webp/1*ohXKD3FJhC0E-8bj_DWTOw.jpeg)


NumPy stands for Numerical Python. 

    - Most important foundational packages for numerical computing & data analysis in Python. 
    - NumPy is used because it makes numerical computation fast, memory-efficient, and scalable.

⭐ Why NumPy is Used: 

    - High performance (very fast)
        - NumPy operations are implemented in C → much faster than Python loops.

    - Vectorized operations
        - Operate on entire arrays at once (no for loops).

    - Efficient memory usage
        - Stores data in contiguous memory with fixed data types.

    - Foundation of data science stack
        - Pandas, SciPy, Scikit-learn, TensorFlow all rely on NumPy.

    - Mathematical & scientific power
        - Linear algebra, statistics, random numbers, FFTs—all built in.

## 1. Creating numpy arrays 

In [38]:
import numpy as np

In [39]:
# Getting nformation about a numpy function 
import sys
print(np.info(np.add, output=sys.stdout))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [41]:
# Create a NumPy array from a list
li = [1, 2, 3, 4, 5, 6, 7] 
print(np.array(li))
np.array(li)

[1 2 3 4 5 6 7]


array([1, 2, 3, 4, 5, 6, 7])

In [42]:
# Create a NumPy array from a tuple
tup = (1, 2, 3, 4, 5, 6, 7)
print(np.array(tup))

[1 2 3 4 5 6 7]


In [43]:
# Create a NumPy array using fromiter()
iterable = (a for a in range(6))
print(np.fromiter(iterable, float))

[0. 1. 2. 3. 4. 5.]


In [44]:
# Create Numpy array from a list 
# create a NumPy array from a list
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
print(np.array([list_1, list_2, list_3]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
# Create a NumPy array using numpy.empty()
print(np.empty([4, 3], dtype=int))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


## 2. Inspecting properties

In [47]:
arr = np.asarray((1,2,3,4,5,6,7))
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
arr_all = (np.array([list_1, list_2, list_3]))
print(arr_all)

# check size of the array
print("Size:", arr.size) # 1-D array 
print("Size:", arr_all.size) # 2-D array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Size: 7
Size: 12


In [48]:
# check len of the array
print("len:", len(arr))

len: 7


In [49]:
# check shape of the array
print("Shape of arr:", arr.shape)
print("Shape of arr_all:", arr_all.shape)

Shape of arr: (7,)
Shape of arr_all: (3, 4)


In [50]:
# check dtype of the array elements
print("Datatype:", arr.dtype)

Datatype: int64


In [51]:
# change the dtype to 'float64'
arr = arr.astype('float64')
print(arr)
print("Datatype:", arr.dtype)

[1. 2. 3. 4. 5. 6. 7.]
Datatype: float64


In [52]:
# convert array to list
lis = arr.tolist()
print("\nList:", lis)
print(type(lis))


List: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]
<class 'list'>


## 3. Initial Placeholders of 1-d numpy arrays 

In [54]:
# create NumPy array using numpy.arange()
print(np.arange(1, 5))

# create NumPy array using numpy.zeros()
print(np.zeros(7, dtype=int))

# create NumPy array using numpy.ones()
print(np.ones(7, dtype=int))

# create NumPy array using numpy.random.rand()
print(np.random.rand(10))

# create NumPy array using numpy.random.randint()
print(np.random.randint(7, size=10))

# create NumPy array using numpy.linspace()
print(np.linspace(1, 10, 4))

[1 2 3 4]
[0 0 0 0 0 0 0]
[1 1 1 1 1 1 1]
[0.52224737 0.90713034 0.26487446 0.54262558 0.27589814 0.09571815
 0.97207515 0.88486728 0.10126592 0.12489133]
[5 3 0 4 5 6 3 1 1 0]
[ 1.  4.  7. 10.]


## 4. Initial placeholders for 2-D array

In [22]:
# create NumPy array using numpy.zeros()
print(np.zeros([2, 2], dtype = np.int8))

# create NumPy array using numpy.ones()
print(np.ones([3, 3], dtype = np.int8))

# create NumPy array using numpy.full()
print(np.full([5, 3], 77, dtype = int))

# create NumPy array using numpy.eye()
print(np.eye(5))

[[0 0]
 [0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[77 77 77]
 [77 77 77]
 [77 77 77]
 [77 77 77]
 [77 77 77]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 5. Saving and loading file 

In [55]:
# save numpy array in .npy file 
np.save("test", np.arange(5))

# the array is loaded into b
print(np.load("test.npy"))

[0 1 2 3 4]


In [56]:
# save numpy array in .txt file 
x = np.arange(0, 10, 1)
print(x)

# X array saved in geekfile.txt
c = np.savetxt("test.txt", x, delimiter =', ')

[0 1 2 3 4 5 6 7 8 9]


In [57]:
# loading from text file 
d = np.loadtxt("test.txt")
print(d)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [58]:
Data = np.genfromtxt("sales_data.csv", delimiter=",")
print(Data)

[[  nan   nan   nan ...   nan   nan   nan]
 [1001.   nan   nan ...   nan   nan 4113.]
 [1002.   nan   nan ...   nan   nan   nan]
 ...
 [1098.   nan   nan ...   nan   nan 2297.]
 [1099.   nan   nan ...   nan   nan   nan]
 [1100.   nan   nan ...   nan   nan   nan]]


In [59]:
# Arithmetic operations 
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a + b

array([ 6,  8, 10, 12])

In [61]:
a+10

array([11, 12, 13, 14])

In [62]:
# 2-D array 
A = np.ones((2, 2))
B = np.ones((2, 2))
A + B

array([[2., 2.],
       [2., 2.]])

In [64]:
arr_data = np.array([
    [25, 175, 70],  # [Age, Height, Weight]
    [30, 180, 80],
    [22, 165, 65],
    [28, 172, 75],
    [35, 178, 85]
])

In [67]:
np.mean(arr_data[:, 0])

np.float64(28.0)

In [68]:
## Compute the statistics for each feature 
arr_data = np.array([
    [25, 175, 70],  # [Age, Height, Weight]
    [30, 180, 80],
    [22, 165, 65],
    [28, 172, 75],
    [35, 178, 85]
])

# 
age_mean = np.mean(arr_data[:, 0])
height_mean = np.mean(arr_data[:, 1])
weight_mean = np.mean(arr_data[:, 2])
print(f"Mean Age: {age_mean}, Mean Height: {height_mean}, Mean Weight: {weight_mean}")

Mean Age: 28.0, Mean Height: 174.0, Mean Weight: 75.0


In [69]:
# Calculate the correlation matrix
corr_matrix = np.corrcoef(arr_data.T)  # Transpose to compute correlation between columns
print("Correlation Matrix:\n", corr_matrix)

Correlation Matrix:
 [[1.         0.78250805 0.99025868]
 [0.78250805 1.         0.83449195]
 [0.99025868 0.83449195 1.        ]]


In [70]:
arr_data.T

array([[ 25,  30,  22,  28,  35],
       [175, 180, 165, 172, 178],
       [ 70,  80,  65,  75,  85]])

## 6. Referencing, Indexing, slicing

In [57]:
arr = np.array([[ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

In [58]:
# 1st row 
arr[0]

array([1, 2, 3, 4, 5])

In [59]:
# 1st column
arr[:, 0]

array([ 1,  6, 11, 16])

In [53]:
# 4th row, 1st column
arr[3][0]

np.int64(16)

In [56]:
# last column 
arr[:, -1]

array([ 5, 10, 15, 20])

## 7. Reshaping & Resizing a numpy array

In [3]:
import numpy as np

In [60]:
arr = np.arange(0, 10, 1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# reshape() — Change shape, NOT data; Original data remains the same 
b = arr.reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
# resize() — Change shape AND data - Original data changed (No need of assignment operator)
arr.resize(2, 5)

print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## 8. Broadcasting exercise
    - Perform operations on arrays of different shapes without explicitly copying data

In [33]:
arr_2d_broadcast = np.random.randint(1, 11, (3, 4)) # stretches the smaller array to match the shape of the larger one virtually
print("2D Array for Broadcasting:\n", arr_2d_broadcast)

2D Array for Broadcasting:
 [[ 7  2  2 10]
 [10  7  5  4]
 [ 7  6 10  1]]


In [65]:
# np.random.randint(1, 11, (3, 7))

In [35]:
# Scalar Broadcasting 
a = np.array([1, 2, 3])
b = a + 10

print(b) # 10 is broadcasted ti [10, 10, 10]

[11 12 13]


In [36]:
# Braodcasting with 2D arrays
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b) # b is stretched across rows

[[11 22 33]
 [14 25 36]]


In [72]:
# Real usecase (Practical use)
# Column-wise substraction using broadcasting
X = np.array([[1, 2],
              [30, 42],
              [5, 6]])

mean = X.mean(axis=0)
print("Mean: ", mean)

X_centered = X - mean # How far is the datapoint from mean 
X_centered

Mean:  [12.         16.66666667]


array([[-11.        , -14.66666667],
       [ 18.        ,  25.33333333],
       [ -7.        , -10.66666667]])

In [73]:
X = np.array([[1, 2],
              [30, 42],
              [5, 6]])
X

array([[ 1,  2],
       [30, 42],
       [ 5,  6]])

In [77]:
X.mean(axis=1)

array([ 1.5, 36. ,  5.5])

## 9. Statistical operation

In [67]:
arr_stat = np.random.randint(0, 10, 100)
arr_stat

array([1, 3, 3, 2, 7, 7, 1, 7, 9, 5, 0, 9, 2, 6, 7, 7, 7, 3, 9, 0, 3, 4,
       9, 9, 6, 7, 0, 9, 2, 4, 7, 0, 3, 4, 6, 7, 5, 3, 1, 5, 6, 8, 4, 6,
       6, 3, 4, 6, 8, 5, 7, 5, 3, 3, 8, 4, 2, 2, 0, 6, 8, 4, 4, 6, 5, 5,
       0, 0, 4, 4, 4, 9, 8, 9, 9, 3, 1, 2, 1, 7, 2, 2, 9, 1, 2, 2, 9, 2,
       8, 0, 4, 3, 4, 3, 2, 2, 3, 7, 6, 7])

In [68]:
min_val = np.min(arr_stat)
max_val = np.max(arr_stat)
mean_val = np.mean(arr_stat)
median_val = np.median(arr_stat)
std_dev = np.std(arr_stat)
print(f"Min: {min_val}, Max: {max_val}, Mean: {mean_val}, Median: {median_val}, Std Dev: {std_dev}")

Min: 0, Max: 9, Mean: 4.56, Median: 4.0, Std Dev: 2.739781013146854


In [80]:
help(np.asarray(5))

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any object that can

In [82]:
arr = np.asarray((1,2,3,4,5,6,7))
arr

array([1, 2, 3, 4, 5, 6, 7])

In [83]:
arr = np.array((1,2,3,4,5,6,7))
arr

array([1, 2, 3, 4, 5, 6, 7])

In [87]:
arr = np.array([[np.arange(1, 5), np.arange(1, 5), np.arange(1, 5)], 
               [np.arange(1, 5), np.arange(1, 5), np.arange(1, 5)],
               [np.arange(1, 5), np.arange(1, 5), np.arange(1, 5)]])
arr

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [89]:
np.mean(arr, axis=0)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])