<img src="img.png" width="700">

In this activity we're going to see the evolution of Natural Language Processing from 

Non-neural network method -> NN methods/models -> LLMs

In [ ]:
sentences = [
    "I love machine learning",
    "I love deep learning",
    "I hate bugs in code",
    "Machine learning is powerful"
]

# 1. Non-NN Methods/Traditional NLP

    - These methods completely rely 
        - frequency 
        - probability

## 1.0 Text Preprocessing (Foundation layer of NLP)
    - Tokenization
    - Stopwords
    - Stemming
    - Lemmatization

## 1.1 CountVectorizer (Bag of Words)

 - What It Does
    - Counts word frequency.
    - Ignores word order & context.

 - Significance
    - First practical NLP representation
    - Simple, fast
    - Works well for basic classification
 - Cons
    - No word order 
    - No meaning



In [9]:
from sklearn.feature_extraction.text import CountVectorizer

sentences = [
    "I am happy with this product",
    "I am unhappy with this service",
    "I am satisfied with this purchase",
    "I am disappointed with this experience"
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(sentences)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("Bag of Words Matrix:\n", X.toarray())

Vocabulary: ['am' 'disappointed' 'experience' 'happy' 'product' 'purchase' 'satisfied'
 'service' 'this' 'unhappy' 'with']
Bag of Words Matrix:
 [[1 0 0 1 1 0 0 0 1 0 1]
 [1 0 0 0 0 0 0 1 1 1 1]
 [1 0 0 0 0 1 1 0 1 0 1]
 [1 1 1 0 0 0 0 0 1 0 1]]


## 1.2. TF-IDF (Term Frequency – Inverse Document Frequency)
 - What It Does
    - Weights words based on importance:
    - Common words → lower weight
 - Rare but important words → higher weight

 - Significance
    - Improved BoW
    - Reduces dominance of frequent words
    - Still no context understanding
 - Cons 
    - No context

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(sentences)

print("TF-IDF Matrix:\n", X_tfidf.toarray())

TF-IDF Matrix:
 [[0.         0.         0.         0.         0.         0.
  0.49681612 0.61366674 0.61366674 0.        ]
 [0.         0.         0.70203482 0.         0.         0.
  0.44809973 0.55349232 0.         0.        ]
 [0.5        0.5        0.         0.5        0.5        0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.57457953
  0.36674667 0.         0.4530051  0.57457953]]


## 1.* Other methods - 
    - N-grams
    - Statistical & Probablistic models
    - Topic modelling
    - Matrix methods

# 2. Word Representation Learning - Word Embeddings (Word2Vec / GloVe)
 * Word2vec - Shallow NN (Not DNN)
 * Glove - Matrix factorization based/Word co-occurance matrix


 - What It Does
    - Represents words as dense vectors.
    - Captures semantic similarity.

    ** king - man + woman ≈ queen

 - Significance
    - Captures meaning/semantic similarity
    - Words close in vector space = similar meaning
    - Still static (one meaning per word)
 - Cons - 
    - Static word meaning

In [3]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 462.3 kB/s  0:00:51m0:00:0100:02


In [5]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/gourasundarmohanty/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
# Word2Vec using gensim
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize

tokenized_sentences = [word_tokenize(sentence.lower()) for sentence in sentences]

model = Word2Vec(sentences=tokenized_sentences, vector_size=50, window=2, min_count=1)

print("Vector for 'learning':\n", model.wv['learning'])
print("Most similar to 'machine':\n", model.wv.most_similar('machine'))

Vector for 'learning':
 [-1.0724545e-03  4.7286271e-04  1.0206699e-02  1.8018546e-02
 -1.8605899e-02 -1.4233618e-02  1.2917745e-02  1.7945977e-02
 -1.0030856e-02 -7.5267432e-03  1.4761009e-02 -3.0669428e-03
 -9.0732267e-03  1.3108104e-02 -9.7203208e-03 -3.6320353e-03
  5.7531595e-03  1.9837476e-03 -1.6570430e-02 -1.8897636e-02
  1.4623532e-02  1.0140524e-02  1.3515387e-02  1.5257311e-03
  1.2701781e-02 -6.8107317e-03 -1.8928028e-03  1.1537147e-02
 -1.5043275e-02 -7.8722071e-03 -1.5023164e-02 -1.8600845e-03
  1.9076237e-02 -1.4638334e-02 -4.6675373e-03 -3.8754821e-03
  1.6154874e-02 -1.1861792e-02  9.0324880e-05 -9.5074680e-03
 -1.9207101e-02  1.0014586e-02 -1.7519170e-02 -8.7836506e-03
 -7.0199967e-05 -5.9236289e-04 -1.5322480e-02  1.9229487e-02
  9.9641159e-03  1.8466286e-02]
Most similar to 'machine':
 [('powerful', 0.16563552618026733), ('bugs', 0.13940520584583282), ('learning', 0.1267007291316986), ('deep', 0.1211962029337883), ('code', 0.08872982859611511), ('i', 0.01107198838144

In [ ]:
# pip install gensim

  Using cached smart_open-7.5.0-py3-none-any.whl.metadata (24 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.4/24.4 MB 4.8 MB/s  0:00:05 eta 0:00:01
Using cached smart_open-7.5.0-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [gensim]2m1/2 [gensim]
Note: you may need to restart the kernel to use updated packages.


In [24]:
# king - man + woman ≈ queen
# Load pretrained model (this may take time first time)
import gensim.downloader as api
model = api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [25]:
# Perform vector arithmetic 
result = model.most_similar(
    positive=["king", "woman"],
    negative=["man"],
    topn=5
)

print(result)


[('queen', 0.7118192911148071), ('monarch', 0.6189674735069275), ('princess', 0.5902431011199951), ('crown_prince', 0.5499460697174072), ('prince', 0.5377321243286133)]


In [26]:
# manually check the vector 
import numpy as np

vector = model["king"] - model["man"] + model["woman"]

similarities = model.similar_by_vector(vector, topn=5)
print(similarities)

[('king', 0.8449392318725586), ('queen', 0.7300516366958618), ('monarch', 0.6454660296440125), ('princess', 0.6156251430511475), ('crown_prince', 0.5818676948547363)]


# 3. NN Methods - Sequence learning

## 3.1 RNN (Recurrent Neural Network)
 - What It Does
    - Processes sequences word-by-word.
    - Remembers previous context (short-term memory).
 - Significance
    - Understands word order
    - Better for sequences
    - Struggles with long dependencies (vanishing gradient)

 - Applications 
   - Time-series prediction
   - NLP
   - Speech recognition 
   - Image and video processing
 - Cons 
   - Vanishing gradient/exploding gradient 
   - Poor long term memory


In [2]:
!pip install tensorflow

  Using cached absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-1-py2.py3-none-macosx_11_0_arm64.whl.metadata (5.2 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached protobuf-6.33.5-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
  Using cached keras-3.13.2-py3-none-any.whl.metadata (6.3 kB)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
  Using cached werkzeug-3.1.5-py3-none-any.whl.metadata (4.0 kB)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
   ━━━━

In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

In [4]:
# Define input text and identify unique characters in the text which we’ll encode for our model.
text = "Welcom to IITM Pravartak program, focused on learning Agentic AI, Generative AI systems and it's practical implications"
chars = sorted(list(set(text)))
char_to_index = {char: i for i, char in enumerate(chars)}
index_to_char = {i: char for i, char in enumerate(chars)}

In [5]:
# To train the RNN, we need sequences of fixed length (seq_length) and the character following each sequence as the label.
seq_length = 3
sequences = []
labels = []

for i in range(len(text) - seq_length):
    seq = text[i:i + seq_length]
    label = text[i + seq_length]
    sequences.append([char_to_index[char] for char in seq])
    labels.append(char_to_index[label])

X = np.array(sequences)
y = np.array(labels)

In [6]:
# Converting Sequences and Labels to One-Hot Encoding
X_one_hot = tf.one_hot(X, len(chars))
y_one_hot = tf.one_hot(y, len(chars))

In [7]:
# Create a simple RNN model with a hidden layer of 50 units and a Dense output layer with softmax activation
model = Sequential()
model.add(SimpleRNN(50, input_shape=(seq_length, len(chars)), activation='relu'))
model.add(Dense(len(chars), activation='softmax'))

/Users/gourasundarmohanty/miniconda3/envs/py313/lib/python3.13/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [8]:
# Compile the model using the categorical_crossentropy loss and train it for 100 epochs
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_one_hot, y_one_hot, epochs=100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.0172 - loss: 3.3457  
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0345 - loss: 3.3090     
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1121 - loss: 3.2777     
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1207 - loss: 3.2457     
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1724 - loss: 3.2133 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1983 - loss: 3.1806 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2155 - loss: 3.1445 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2155 - loss: 3.1068 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2069 - loss: 3.0699 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2069 - loss: 3.0272 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2155 - loss: 2.9845 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy:

In [9]:
# Testing - After training we use a starting sequence to generate new text character by character
start_seq = "focused on"
generated_text = start_seq

for i in range(50):
    x = np.array([[char_to_index[char] for char in generated_text[-seq_length:]]])
    x_one_hot = tf.one_hot(x, len(chars))
    prediction = model.predict(x_one_hot)
    next_index = np.argmax(prediction)
    next_char = index_to_char[next_index]
    generated_text += next_char

print("Generated Text:")
print(generated_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━

## 3.2 LSTM (Long Short-Term Memory)
 - What It Does
    - Improved RNN with memory gates:
    - Forget gate
    - Input gate
    - Output gate

 - Significance
    - Handles long-term dependencies better
    - Used in translation, speech recognition (pre-transformer era)

 - Cons 
   - Slow inference
   - Limited memory
   - Context fade over very long sequence
   - Hard to scale

In [ ]:
pip install pandas scikit-learn matplotlib

  Using cached pandas-3.0.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 4.0 MB/s  0:00:02 eta 0:00:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 4.6 MB/s  0:00:01 eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 4.0 MB/s  0:00:02 eta 0:00:01
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 4.1 MB/s  0:00:00 eta 0:00:01
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.1/20.1 MB 4.2 MB/s  0:00:04m0:00:0100:01
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/11 [matplotlib]1 [matplotlib]n]
Note: you may need to restart the kernel to use 

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

In [17]:
data = pd.read_csv('monthly_milk_production.csv')
data['Date'] = pd.to_datetime(data['Date'])
data.set_index('Date', inplace=True)
production = data['Production'].astype(float).values.reshape(-1, 1)

scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(production)

In [18]:
# Creating Sequences and Train-Test Split
window_size = 12
X = []
y = []
target_dates = data.index[window_size:]

for i in range(window_size, len(scaled_data)):
    X.append(scaled_data[i - window_size:i, 0])
    y.append(scaled_data[i, 0])

X = np.array(X)
y = np.array(y)

X_train, X_test, y_train, y_test, dates_train, dates_test = train_test_split(
    X, y, target_dates, test_size=0.2, shuffle=False
)

X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

In [19]:
# Build LSTM model
model = Sequential()
model.add(LSTM(units=128, return_sequences=True,
          input_shape=(X_train.shape[1], 1)))
model.add(Dropout(0.2))
model.add(LSTM(units=128))
model.add(Dropout(0.2))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mean_squared_error')

/Users/gourasundarmohanty/miniconda3/envs/py313/lib/python3.13/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [20]:
# Training and Evaluation 
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.1)

predictions = model.predict(X_test)
predictions = scaler.inverse_transform(predictions).flatten()
y_test = scaler.inverse_transform(y_test.reshape(-1,1)).flatten()

rmse = np.sqrt(np.mean((y_test - predictions)**2))
print(f'RMSE: {rmse:.2f}')

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 99ms/step - loss: 0.1205 - val_loss: 0.0268
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0509 - val_loss: 0.0369
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0281 - val_loss: 0.0708
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0424 - val_loss: 0.0692
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0318 - val_loss: 0.0284
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0245 - val_loss: 0.0290
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0298 - val_loss: 0.0259
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0262 - val_loss: 0.0390
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0272 - val_loss: 0.0442
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0274 - val_loss: 0.0307
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0240 - val_loss: 0.0252
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0262 - val_lo

<img src="img2.png" width="500">

## 3.3 A tiny NN language model 

- What is a Language Model? 
    - A language model predicts: P(next_word∣previous_words)

In [28]:
!pip install torch

  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 MB 4.3 MB/s  0:00:18m0:00:0100:01
Using cached fsspec-2026.2.0-py3-none-any.whl (202 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 6.3 MB/s  0:00:00 eta 0:00:01
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [torch]32m5/6 [torch]]x]


In [29]:
import torch
import torch.nn as nn
import torch.optim as optim

# Sample dataset
text = "i love machine learning and i love deep learning"
words = text.split()

# Vocabulary
vocab = list(set(words))
word_to_ix = {word: i for i, word in enumerate(vocab)}
ix_to_word = {i: word for word, i in word_to_ix.items()}

# Prepare training data (input -> next word)
inputs = []
targets = []

for i in range(len(words)-1):
    inputs.append(word_to_ix[words[i]])
    targets.append(word_to_ix[words[i+1]])

inputs = torch.tensor(inputs)
targets = torch.tensor(targets)

# Model
class TinyLanguageModel(nn.Module):
    def __init__(self, vocab_size, embed_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)
        self.linear = nn.Linear(embed_size, vocab_size)

    def forward(self, x):
        x = self.embedding(x)
        x = self.linear(x)
        return x

model = TinyLanguageModel(len(vocab), 10)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
for epoch in range(200):
    optimizer.zero_grad()
    output = model(inputs)
    loss = criterion(output, targets)
    loss.backward()
    optimizer.step()

# Test prediction
with torch.no_grad():
    test_word = "i"
    test_input = torch.tensor([word_to_ix[test_word]])
    output = model(test_input)
    predicted = torch.argmax(output).item()

print("After 'i' predicted word:", ix_to_word[predicted])

After 'i' predicted word: love


In [30]:
# Test prediction
with torch.no_grad():
    test_word = "deep"
    test_input = torch.tensor([word_to_ix[test_word]])
    output = model(test_input)
    predicted = torch.argmax(output).item()

print("After 'deep' predicted word:", ix_to_word[predicted])

After 'deep' predicted word: learning
