In [2]:
import numpy as np

# **Exercise 1: Creating and Manipulating NumPy Arrays**

# 1. Create a 1D NumPy array
arr = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr)

# 2. Perform element-wise addition
arr_add = arr + 10
print("Array after adding 10:", arr_add)

# 3. Create a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

# 4. Indexing Exercise: Access and print the second row
second_row = arr_2d[1]
print("Second Row:", second_row)

# 5. Slice the array to extract the first 3 elements
arr_slice = arr[:3]
print("Sliced Array (First 3 elements):", arr_slice)

# 6. Perform element-wise multiplication
arr2 = np.array([2, 3, 4, 5, 6])
arr_multiply = arr * arr2
print("Array after element-wise multiplication:", arr_multiply)

# **Exercise 2: NumPy Array Operations**

# 1. Create a 1D array of 10 random numbers between 0 and 100
arr_random = np.random.randint(0, 101, 10)
print("Random Array:", arr_random)

# 2. Find the sum, mean, and standard deviation of the array
sum_val = np.sum(arr_random)
mean_val = np.mean(arr_random)
std_dev = np.std(arr_random)
print(f"Sum: {sum_val}, Mean: {mean_val}, Std Dev: {std_dev}")

# 3. Create a 2D array (3x3) of random integers between 1 and 100
arr_2d_random = np.random.randint(1, 101, (3, 3))
print("2D Random Array:\n", arr_2d_random)

# 4. Perform operations on the 2D array
# - Sum of each column
col_sum = np.sum(arr_2d_random, axis=0)
print("Sum of each column:", col_sum)

# - Mean of each row
row_mean = np.mean(arr_2d_random, axis=1)
print("Mean of each row:", row_mean)

# **Exercise 3: Advanced Operations and Reshaping**

# 1. Create a 1D array of 12 elements with values from 1 to 12
arr_12 = np.arange(1, 13)
print("1D Array of 12 elements:", arr_12)

# 2. Reshape the array into a 3x4 2D array
arr_reshaped = arr_12.reshape(3, 4)
print("Reshaped Array (3x4):\n", arr_reshaped)

# 3. Broadcasting Exercise
# Create a 2D array with shape (3, 4) filled with random integers
arr_2d_broadcast = np.random.randint(1, 11, (3, 4))
print("2D Array for Broadcasting:\n", arr_2d_broadcast)

# Add a 1D array of shape (4,) to the 2D array
arr_broadcasted = arr_2d_broadcast + np.array([1, 2, 3, 4])
print("Array after Broadcasting:\n", arr_broadcasted)

# **Exercise 4: Working with Statistical Functions**

# 1. Create a random 1D array of 100 numbers between 0 and 50
arr_stat = np.random.randint(0, 51, 100)
print("Random 1D Array for Stats:", arr_stat)

# 2. Calculate and print the following statistics for the array
min_val = np.min(arr_stat)
max_val = np.max(arr_stat)
mean_val = np.mean(arr_stat)
median_val = np.median(arr_stat)
std_dev = np.std(arr_stat)
print(f"Min: {min_val}, Max: {max_val}, Mean: {mean_val}, Median: {median_val}, Std Dev: {std_dev}")

# 3. Create a 2D array of shape (5, 4)
arr_2d_stat = np.random.randint(1, 101, (5, 4))
print("2D Array for Stats:\n", arr_2d_stat)

# - Sum of all elements
arr_sum = np.sum(arr_2d_stat)
print("Sum of all elements:", arr_sum)

# - Mean of each column
arr_col_mean = np.mean(arr_2d_stat, axis=0)
print("Mean of each column:", arr_col_mean)

# **Challenge Exercise: Real-World Application**

# 1. Create a 2D NumPy array representing the dataset
arr_data = np.array([
    [25, 175, 70],  # [Age, Height, Weight]
    [30, 180, 80],
    [22, 165, 65],
    [28, 172, 75],
    [35, 178, 85]
])
print("Dataset (Age, Height, Weight):\n", arr_data)

# 2. Compute the statistics for each feature (Age, Height, Weight)
age_mean = np.mean(arr_data[:, 0])
height_mean = np.mean(arr_data[:, 1])
weight_mean = np.mean(arr_data[:, 2])
print(f"Mean Age: {age_mean}, Mean Height: {height_mean}, Mean Weight: {weight_mean}")

age_std = np.std(arr_data[:, 0])
height_std = np.std(arr_data[:, 1])
weight_std = np.std(arr_data[:, 2])
print(f"Std Dev Age: {age_std}, Std Dev Height: {height_std}, Std Dev Weight: {weight_std}")

# 3. Calculate the correlation matrix
corr_matrix = np.corrcoef(arr_data.T)  # Transpose to compute correlation between columns
print("Correlation Matrix:\n", corr_matrix)


1D Array: [10 20 30 40 50]
Array after adding 10: [20 30 40 50 60]
2D Array:
 [[1 2 3]
 [4 5 6]]
Second Row: [4 5 6]
Sliced Array (First 3 elements): [10 20 30]
Array after element-wise multiplication: [ 20  60 120 200 300]
Random Array: [67 52 11 70 35 97 36 75 76  6]
Sum: 525, Mean: 52.5, Std Dev: 28.316956051101254
2D Random Array:
 [[69 80 85]
 [45 15 69]
 [37  6 68]]
Sum of each column: [151 101 222]
Mean of each row: [78. 43. 37.]
1D Array of 12 elements: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2D Array for Broadcasting:
 [[ 5  5  9  1]
 [ 2  3  9  7]
 [ 1 10  3  1]]
Array after Broadcasting:
 [[ 6  7 12  5]
 [ 3  5 12 11]
 [ 2 12  6  5]]
Random 1D Array for Stats: [15 46 44 17 45  1 12 40  2 14  6 27 35 24 13 22 13 35  1 37 41 25 40 14
 37  1 35  9 44 10 44 30  7 14 41 48 25  9 48 37 15 26 45 14  5  6 48 33
 35  9 47 18 24 39 48 48 38 42 42 39 19 39  7 17 24 24 18 12 32 16 19 40
 32  0  1  9  7  7 30  9 22 22 33 